### ISSUE TITLE
Having an issue using the package, followed the vanila php usage

### ISSUE THREAD

**Issue by evilboss** [CoreProc/paynamics-sdk-laravel#2]
basically here is the code i did to implement your lib

`
require_once 'vendor/autoload.php';

$client = new \CoreProc\Paynamics\Paygate\Client([
    'merchant_id' => 'xxxxxxxxxxx',
    'merchant_key' => 'xxxxxxxxxx',
    'sandbox' => true,
    'sandbox_url' => 'https://testpti.payserv.net/webpayment/Default.aspx',
    'production_url' => 'PRODUCTION URL',
]);
$requestBody = new \CoreProc\Paynamics\Paygate\RequestBody([
    'request_id' => substr(uniqid(), 1, 13),
    'fname' => 'Paynamics',
    'lname' => 'Buyer',
    'address1' => '101 Oval St.',
    'city' => 'Pasig City',
    'state' => 'Metro Manila',
    'country' => 'PH',
    'zip' => '1600',
    'email' => 'buyer@example.com',
    'phone' => '+63 123 4567',
    'mobile' => '+63 999 123 4567',
    'currency' => 'PHP',
    'descriptor_note' => 'PayGate Sample Merchant',

    'notification_url' => 'http://example.com/notify',
    'response_url' => 'http://example.com/success',
    'cancel_url' => 'http://example.com/cancel',
    'mtac_url' => 'http://example.com/tnc',
    'mlogo_url' => 'http://example.com/assets/logo.png',
]);
$item = new \CoreProc\Paynamics\Paygate\Item;
$items = new \CoreProc\Paynamics\Paygate\ItemGroup;
$item->setName('Sample Item');
$item->setAmount(100);
$item->setQuantity(1);
$items->addItem($item);
$requestBody->setItemGroup($items);
$client->send($requestBody);
`

I keep getting this error 
`**Fatal error: Interface 'Coreproc\Paynamics\Paygate\Contracts\ResponseInterface' not found in /Users/evilboss/Projects/ptsi/donation-page/vendor/paynamics/paygate-sdk-php/src/Response.php on line 7**`

**Comment by jacob2790** [comment]
Same issue for me.

**Comment by chrisbjr** [comment]
Previous version for vanilla PHP usage has been abandoned. This package has now been updated solely for Laravel use. Thanks.
